### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by frankluebeck** [gap-packages/liepring#24]
When testing the GAP 4.12.0 release with LiePRing 2.7 I got the following warning:
```
Syntax warning: Unbound global variable in /cache/gap-4.12.0/pkg/liepring/gap/\
advan/schur.gi:339
    G := List(F, x -> PcGroupToPcpGroup(PGroupByLiePRing(x)));
                      ^^^^^^^^^^^^^^^^^
Syntax warning: Unbound global variable in /cache/gap-4.12.0/pkg/liepring/gap/\
advan/schur.gi:340
    c := Collected(List(G, SchurMultPcpGroup));
                           ^^^^^^^^^^^^^^^^^
```

I guess that the `polycyclic` should be added as needed package in your `PackageInfo.g` file.

**Comment by fingolfin** [comment]
The offending code is only used for internal consistency tests. So instead of adding a dependency on polycyclic, we should just move this into a file that is not loaded by default.
